/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IBridge {
  export type UserStruct = {
    _address: PromiseOrValue<string>;
    chainId: PromiseOrValue<BigNumberish>;
  };

  export type UserStructOutput = [string, BigNumber] & {
    _address: string;
    chainId: BigNumber;
  };

  export type OriginalTokenStruct = {
    tokenAddress: PromiseOrValue<string>;
    originChainId: PromiseOrValue<BigNumberish>;
  };

  export type OriginalTokenStructOutput = [string, BigNumber] & {
    tokenAddress: string;
    originChainId: BigNumber;
  };

  export type SourceTxDataStruct = {
    transactionHash: PromiseOrValue<BytesLike>;
    blockHash: PromiseOrValue<BytesLike>;
    logIndex: PromiseOrValue<BigNumberish>;
  };

  export type SourceTxDataStructOutput = [string, string, BigNumber] & {
    transactionHash: string;
    blockHash: string;
    logIndex: BigNumber;
  };

  export type ClaimDataStruct = {
    from: IBridge.UserStruct;
    to: IBridge.UserStruct;
    value: PromiseOrValue<BigNumberish>;
    token: IBridge.OriginalTokenStruct;
    depositTxSourceToken: PromiseOrValue<string>;
    targetTokenAddress: PromiseOrValue<string>;
    targetTokenName: PromiseOrValue<string>;
    targetTokenSymbol: PromiseOrValue<string>;
    deadline: PromiseOrValue<BigNumberish>;
    sourceTxData: IBridge.SourceTxDataStruct;
  };

  export type ClaimDataStructOutput = [
    IBridge.UserStructOutput,
    IBridge.UserStructOutput,
    BigNumber,
    IBridge.OriginalTokenStructOutput,
    string,
    string,
    string,
    string,
    BigNumber,
    IBridge.SourceTxDataStructOutput
  ] & {
    from: IBridge.UserStructOutput;
    to: IBridge.UserStructOutput;
    value: BigNumber;
    token: IBridge.OriginalTokenStructOutput;
    depositTxSourceToken: string;
    targetTokenAddress: string;
    targetTokenName: string;
    targetTokenSymbol: string;
    deadline: BigNumber;
    sourceTxData: IBridge.SourceTxDataStructOutput;
  };

  export type SignatureStruct = {
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type SignatureStructOutput = [number, string, string] & {
    v: number;
    r: string;
    s: string;
  };

  export type DepositDataStruct = {
    from: IBridge.UserStruct;
    to: IBridge.UserStruct;
    spender: PromiseOrValue<string>;
    token: PromiseOrValue<string>;
    value: PromiseOrValue<BigNumberish>;
    deadline: PromiseOrValue<BigNumberish>;
    approveTokenTransferSig: IBridge.SignatureStruct;
  };

  export type DepositDataStructOutput = [
    IBridge.UserStructOutput,
    IBridge.UserStructOutput,
    string,
    string,
    BigNumber,
    BigNumber,
    IBridge.SignatureStructOutput
  ] & {
    from: IBridge.UserStructOutput;
    to: IBridge.UserStructOutput;
    spender: string;
    token: string;
    value: BigNumber;
    deadline: BigNumber;
    approveTokenTransferSig: IBridge.SignatureStructOutput;
  };
}

export interface BridgeInterface extends utils.Interface {
  functions: {
    "CLAIMDATA_TYPEHASH()": FunctionFragment;
    "CLAIM_TYPEHASH()": FunctionFragment;
    "DOMAIN_SEPARATOR()": FunctionFragment;
    "ORIGINAL_TOKEN_TYPEHASH()": FunctionFragment;
    "SOURCE_TX_DATA_TYPEHASH()": FunctionFragment;
    "USER_TYPEHASH()": FunctionFragment;
    "claim(((address,uint256),(address,uint256),uint256,(address,uint256),address,address,string,string,uint256,(bytes32,bytes32,uint256)),(uint8,bytes32,bytes32))": FunctionFragment;
    "deposit(((address,uint256),(address,uint256),address,address,uint256,uint256,(uint8,bytes32,bytes32)))": FunctionFragment;
    "depositWithPermit(((address,uint256),(address,uint256),address,address,uint256,uint256,(uint8,bytes32,bytes32)))": FunctionFragment;
    "getNumberOfWrappedTokens()": FunctionFragment;
    "isClaimed(bytes32)": FunctionFragment;
    "name()": FunctionFragment;
    "nonce(address)": FunctionFragment;
    "originalTokenByWrappedToken(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "wrappedTokenByOriginalTokenByChainId(uint256,address)": FunctionFragment;
    "wrappedTokens(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CLAIMDATA_TYPEHASH"
      | "CLAIM_TYPEHASH"
      | "DOMAIN_SEPARATOR"
      | "ORIGINAL_TOKEN_TYPEHASH"
      | "SOURCE_TX_DATA_TYPEHASH"
      | "USER_TYPEHASH"
      | "claim"
      | "deposit"
      | "depositWithPermit"
      | "getNumberOfWrappedTokens"
      | "isClaimed"
      | "name"
      | "nonce"
      | "originalTokenByWrappedToken"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "transferOwnership"
      | "unpause"
      | "wrappedTokenByOriginalTokenByChainId"
      | "wrappedTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CLAIMDATA_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CLAIM_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORIGINAL_TOKEN_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOURCE_TX_DATA_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USER_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [IBridge.ClaimDataStruct, IBridge.SignatureStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [IBridge.DepositDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithPermit",
    values: [IBridge.DepositDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getNumberOfWrappedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isClaimed",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nonce",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "originalTokenByWrappedToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "wrappedTokenByOriginalTokenByChainId",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "wrappedTokens",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "CLAIMDATA_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CLAIM_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORIGINAL_TOKEN_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOURCE_TX_DATA_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USER_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumberOfWrappedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "originalTokenByWrappedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wrappedTokenByOriginalTokenByChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wrappedTokens",
    data: BytesLike
  ): Result;

  events: {
    "BurnWrappedToken(address,uint256,address,address,uint256,uint256,address,uint256)": EventFragment;
    "LockOriginalToken(address,uint256,address,address,uint256,uint256)": EventFragment;
    "MintWrappedToken(address,uint256,address,address,uint256,uint256,address,uint256,bytes32,bytes32,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "ReleaseOriginalToken(address,uint256,address,address,uint256,uint256,address,bytes32,bytes32,uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BurnWrappedToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LockOriginalToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintWrappedToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReleaseOriginalToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface BurnWrappedTokenEventObject {
  burnedWrappedTokenAddress: string;
  value: BigNumber;
  sender: string;
  recepient: string;
  sourceChainId: BigNumber;
  toChainId: BigNumber;
  originalTokenAddress: string;
  originalTokenChainId: BigNumber;
}
export type BurnWrappedTokenEvent = TypedEvent<
  [string, BigNumber, string, string, BigNumber, BigNumber, string, BigNumber],
  BurnWrappedTokenEventObject
>;

export type BurnWrappedTokenEventFilter =
  TypedEventFilter<BurnWrappedTokenEvent>;

export interface LockOriginalTokenEventObject {
  lockedTokenAddress: string;
  value: BigNumber;
  sender: string;
  recepient: string;
  sourceChainId: BigNumber;
  toChainId: BigNumber;
}
export type LockOriginalTokenEvent = TypedEvent<
  [string, BigNumber, string, string, BigNumber, BigNumber],
  LockOriginalTokenEventObject
>;

export type LockOriginalTokenEventFilter =
  TypedEventFilter<LockOriginalTokenEvent>;

export interface MintWrappedTokenEventObject {
  mintedTokenAddress: string;
  value: BigNumber;
  sender: string;
  recepient: string;
  sourceChainId: BigNumber;
  toChainId: BigNumber;
  originalTokenAddress: string;
  originalChainId: BigNumber;
  transactionHash: string;
  blockHash: string;
  logIndex: BigNumber;
}
export type MintWrappedTokenEvent = TypedEvent<
  [
    string,
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    string,
    string,
    BigNumber
  ],
  MintWrappedTokenEventObject
>;

export type MintWrappedTokenEventFilter =
  TypedEventFilter<MintWrappedTokenEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface ReleaseOriginalTokenEventObject {
  releasedTokenAddress: string;
  value: BigNumber;
  sender: string;
  recepient: string;
  sourceChainId: BigNumber;
  toChainId: BigNumber;
  sourceWrappedTokenAddress: string;
  transactionHash: string;
  blockHash: string;
  logIndex: BigNumber;
}
export type ReleaseOriginalTokenEvent = TypedEvent<
  [
    string,
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    BigNumber
  ],
  ReleaseOriginalTokenEventObject
>;

export type ReleaseOriginalTokenEventFilter =
  TypedEventFilter<ReleaseOriginalTokenEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface Bridge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BridgeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CLAIMDATA_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    CLAIM_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<[string]>;

    ORIGINAL_TOKEN_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    SOURCE_TX_DATA_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    USER_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    claim(
      _claimData: IBridge.ClaimDataStruct,
      claimSig: IBridge.SignatureStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deposit(
      _depositData: IBridge.DepositDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositWithPermit(
      _depositData: IBridge.DepositDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getNumberOfWrappedTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    isClaimed(
      transactionDataHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    nonce(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    originalTokenByWrappedToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { tokenAddress: string; originChainId: BigNumber }
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wrappedTokenByOriginalTokenByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    wrappedTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  CLAIMDATA_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  CLAIM_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

  ORIGINAL_TOKEN_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  SOURCE_TX_DATA_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  USER_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  claim(
    _claimData: IBridge.ClaimDataStruct,
    claimSig: IBridge.SignatureStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deposit(
    _depositData: IBridge.DepositDataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositWithPermit(
    _depositData: IBridge.DepositDataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getNumberOfWrappedTokens(overrides?: CallOverrides): Promise<BigNumber>;

  isClaimed(
    transactionDataHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  name(overrides?: CallOverrides): Promise<string>;

  nonce(
    _owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  originalTokenByWrappedToken(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber] & { tokenAddress: string; originChainId: BigNumber }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wrappedTokenByOriginalTokenByChainId(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  wrappedTokens(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    CLAIMDATA_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    CLAIM_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

    ORIGINAL_TOKEN_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    SOURCE_TX_DATA_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    USER_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    claim(
      _claimData: IBridge.ClaimDataStruct,
      claimSig: IBridge.SignatureStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    deposit(
      _depositData: IBridge.DepositDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    depositWithPermit(
      _depositData: IBridge.DepositDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    getNumberOfWrappedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    isClaimed(
      transactionDataHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    name(overrides?: CallOverrides): Promise<string>;

    nonce(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    originalTokenByWrappedToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { tokenAddress: string; originChainId: BigNumber }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    wrappedTokenByOriginalTokenByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    wrappedTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "BurnWrappedToken(address,uint256,address,address,uint256,uint256,address,uint256)"(
      burnedWrappedTokenAddress?: null,
      value?: null,
      sender?: PromiseOrValue<string> | null,
      recepient?: PromiseOrValue<string> | null,
      sourceChainId?: null,
      toChainId?: null,
      originalTokenAddress?: PromiseOrValue<string> | null,
      originalTokenChainId?: null
    ): BurnWrappedTokenEventFilter;
    BurnWrappedToken(
      burnedWrappedTokenAddress?: null,
      value?: null,
      sender?: PromiseOrValue<string> | null,
      recepient?: PromiseOrValue<string> | null,
      sourceChainId?: null,
      toChainId?: null,
      originalTokenAddress?: PromiseOrValue<string> | null,
      originalTokenChainId?: null
    ): BurnWrappedTokenEventFilter;

    "LockOriginalToken(address,uint256,address,address,uint256,uint256)"(
      lockedTokenAddress?: PromiseOrValue<string> | null,
      value?: null,
      sender?: PromiseOrValue<string> | null,
      recepient?: PromiseOrValue<string> | null,
      sourceChainId?: null,
      toChainId?: null
    ): LockOriginalTokenEventFilter;
    LockOriginalToken(
      lockedTokenAddress?: PromiseOrValue<string> | null,
      value?: null,
      sender?: PromiseOrValue<string> | null,
      recepient?: PromiseOrValue<string> | null,
      sourceChainId?: null,
      toChainId?: null
    ): LockOriginalTokenEventFilter;

    "MintWrappedToken(address,uint256,address,address,uint256,uint256,address,uint256,bytes32,bytes32,uint256)"(
      mintedTokenAddress?: null,
      value?: null,
      sender?: null,
      recepient?: PromiseOrValue<string> | null,
      sourceChainId?: null,
      toChainId?: null,
      originalTokenAddress?: PromiseOrValue<string> | null,
      originalChainId?: null,
      transactionHash?: PromiseOrValue<BytesLike> | null,
      blockHash?: null,
      logIndex?: null
    ): MintWrappedTokenEventFilter;
    MintWrappedToken(
      mintedTokenAddress?: null,
      value?: null,
      sender?: null,
      recepient?: PromiseOrValue<string> | null,
      sourceChainId?: null,
      toChainId?: null,
      originalTokenAddress?: PromiseOrValue<string> | null,
      originalChainId?: null,
      transactionHash?: PromiseOrValue<BytesLike> | null,
      blockHash?: null,
      logIndex?: null
    ): MintWrappedTokenEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "ReleaseOriginalToken(address,uint256,address,address,uint256,uint256,address,bytes32,bytes32,uint256)"(
      releasedTokenAddress?: PromiseOrValue<string> | null,
      value?: null,
      sender?: null,
      recepient?: PromiseOrValue<string> | null,
      sourceChainId?: null,
      toChainId?: null,
      sourceWrappedTokenAddress?: null,
      transactionHash?: PromiseOrValue<BytesLike> | null,
      blockHash?: null,
      logIndex?: null
    ): ReleaseOriginalTokenEventFilter;
    ReleaseOriginalToken(
      releasedTokenAddress?: PromiseOrValue<string> | null,
      value?: null,
      sender?: null,
      recepient?: PromiseOrValue<string> | null,
      sourceChainId?: null,
      toChainId?: null,
      sourceWrappedTokenAddress?: null,
      transactionHash?: PromiseOrValue<BytesLike> | null,
      blockHash?: null,
      logIndex?: null
    ): ReleaseOriginalTokenEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    CLAIMDATA_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    CLAIM_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<BigNumber>;

    ORIGINAL_TOKEN_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    SOURCE_TX_DATA_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    USER_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      _claimData: IBridge.ClaimDataStruct,
      claimSig: IBridge.SignatureStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deposit(
      _depositData: IBridge.DepositDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositWithPermit(
      _depositData: IBridge.DepositDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getNumberOfWrappedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    isClaimed(
      transactionDataHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    nonce(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    originalTokenByWrappedToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wrappedTokenByOriginalTokenByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    wrappedTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CLAIMDATA_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CLAIM_TYPEHASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ORIGINAL_TOKEN_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SOURCE_TX_DATA_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    USER_TYPEHASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claim(
      _claimData: IBridge.ClaimDataStruct,
      claimSig: IBridge.SignatureStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deposit(
      _depositData: IBridge.DepositDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositWithPermit(
      _depositData: IBridge.DepositDataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getNumberOfWrappedTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isClaimed(
      transactionDataHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nonce(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    originalTokenByWrappedToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wrappedTokenByOriginalTokenByChainId(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    wrappedTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
