/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Bridge } from "./Bridge";
export type { IBridge } from "./IBridge";
export type { MaliciousPermitERC20 } from "./MaliciousPermitERC20";
export type { PermitERC20 } from "./PermitERC20";
